#include "stm32.h"

struct Stm32RccConfig {
    uint32_t HSI_FREQ;
    uint32_t LSI_FREQ;

    uint8_t RCC_CR_OFFSET;
    uint8_t RCC_CR_PLL3RDY_CL_BIT;
    uint8_t RCC_CR_PLL3ON_CL_BIT;
    uint8_t RCC_CR_PLL2RDY_CL_BIT;
    uint8_t RCC_CR_PLL2ON_CL_BIT;
    uint8_t RCC_CR_PLLRDY_BIT;
    uint8_t RCC_CR_PLLON_BIT;
    uint8_t RCC_CR_CSSON_BIT;
    uint8_t RCC_CR_HSEBYP_BIT;
    uint8_t RCC_CR_HSERDY_BIT;
    uint8_t RCC_CR_HSEON_BIT;
    uint8_t RCC_CR_HSICAL_START;
    uint32_t RCC_CR_HSICAL_MASK;
    uint8_t RCC_CR_HSITRIM_START;
    uint32_t RCC_CR_HSITRIM_MASK;
    uint8_t RCC_CR_HSIRDY_BIT;
    uint8_t RCC_CR_HSION_BIT;

    uint8_t RCC_CFGR_OFFSET;
    uint8_t RCC_CFGR_MCO_START;
    uint32_t RCC_CFGR_MCO_MASK;
    uint32_t RCC_CFGR_MCO_CL_MASK;
    uint8_t RCC_CFGR_USBPRE_BIT;
    uint8_t RCC_CFGR_OTGFSPRE_CL_BIT;
    uint8_t RCC_CFGR_PLLMUL_START;
    uint32_t RCC_CFGR_PLLMUL_MASK;
    uint8_t RCC_CFGR_PLLXTPRE_BIT;
    uint8_t RCC_CFGR_PLLSRC_BIT;
    uint8_t RCC_CFGR_ADCPRE_START;
    uint32_t RCC_CFGR_ADCPRE_MASK;
    uint8_t RCC_CFGR_PPRE2_START;
    uint32_t RCC_CFGR_PPRE2_MASK;
    uint8_t RCC_CFGR_PPRE1_START;
    uint32_t RCC_CFGR_PPRE1_MASK;
    uint8_t RCC_CFGR_HPRE_START;
    uint32_t RCC_CFGR_HPRE_MASK;
    uint8_t RCC_CFGR_SWS_START;
    uint32_t RCC_CFGR_SWS_MASK;
    uint8_t RCC_CFGR_SW_START;
    uint32_t RCC_CFGR_SW_MASK;

    uint8_t RCC_CIR_OFFSET;

    uint8_t RCC_APB2RSTR_OFFSET;

    uint8_t RCC_APB1RSTR_OFFSET;

    uint8_t RCC_AHBENR_OFFSET;

    uint8_t RCC_APB2ENR_OFFSET;
    uint8_t RCC_APB2ENR_ADC3EN_BIT;
    uint8_t RCC_APB2ENR_USART1EN_BIT;
    uint8_t RCC_APB2ENR_TIM8EN_BIT;
    uint8_t RCC_APB2ENR_SPI1EN_BIT;
    uint8_t RCC_APB2ENR_TIM1EN_BIT;
    uint8_t RCC_APB2ENR_ADC2EN_BIT;
    uint8_t RCC_APB2ENR_ADC1EN_BIT;
    uint8_t RCC_APB2ENR_IOPGEN_BIT;
    uint8_t RCC_APB2ENR_IOPFEN_BIT;
    uint8_t RCC_APB2ENR_IOPEEN_BIT;
    uint8_t RCC_APB2ENR_IOPDEN_BIT;
    uint8_t RCC_APB2ENR_IOPCEN_BIT;
    uint8_t RCC_APB2ENR_IOPBEN_BIT;
    uint8_t RCC_APB2ENR_IOPAEN_BIT;
    uint8_t RCC_APB2ENR_AFIOEN_BIT;

    uint8_t RCC_APB1ENR_OFFSET;
    uint8_t RCC_APB1ENR_DACEN_BIT;
    uint8_t RCC_APB1ENR_PWREN_BIT;
    uint8_t RCC_APB1ENR_BKPEN_BIT;
    uint8_t RCC_APB1ENR_CAN2EN_BIT;
    uint8_t RCC_APB1ENR_CAN1EN_BIT;
    uint8_t RCC_APB1ENR_CANEN_BIT;
    uint8_t RCC_APB1ENR_USBEN_BIT;
    uint8_t RCC_APB1ENR_I2C2EN_BIT;
    uint8_t RCC_APB1ENR_I2C1EN_BIT;
    uint8_t RCC_APB1ENR_USART5EN_BIT;
    uint8_t RCC_APB1ENR_USART4EN_BIT;
    uint8_t RCC_APB1ENR_USART3EN_BIT;
    uint8_t RCC_APB1ENR_USART2EN_BIT;
    uint8_t RCC_APB1ENR_SPI3EN_BIT;
    uint8_t RCC_APB1ENR_SPI2EN_BIT;
    uint8_t RCC_APB1ENR_WWDGEN_BIT;
    uint8_t RCC_APB1ENR_TIM7EN_BIT;
    uint8_t RCC_APB1ENR_TIM6EN_BIT;
    uint8_t RCC_APB1ENR_TIM5EN_BIT;
    uint8_t RCC_APB1ENR_TIM4EN_BIT;
    uint8_t RCC_APB1ENR_TIM3EN_BIT;
    uint8_t RCC_APB1ENR_TIM2EN_BIT;

    uint8_t RCC_BDCR_OFFSET;
    uint8_t RCC_BDCR_RTCEN_BIT;
    uint8_t RCC_BDCR_RTCSEL_START;
    uint32_t RCC_BDCR_RTCSEL_MASK;
    uint8_t RCC_BDCR_LSERDY_BIT;
    uint8_t RCC_BDCR_LSEON_BIT;

    uint8_t RCC_CSR_OFFSET;
    uint8_t RCC_CSR_LSIRDY_BIT;
    uint8_t RCC_CSR_LSION_BIT;

    uint8_t RCC_AHBRSTR;

    uint8_t RCC_CFGR2_OFFSET;
    uint8_t RCC_CFGR2_I2S3SRC_BIT;
    uint8_t RCC_CFGR2_I2S2SRC_BIT;
    uint8_t RCC_CFGR2_PREDIV1SRC_BIT;
    uint8_t RCC_CFGR2_PLL3MUL_START;
    uint32_t RCC_CFGR2_PLL3MUL_MASK;
    uint8_t RCC_CFGR2_PLL2MUL_START;
    uint32_t RCC_CFGR2_PLL2MUL_MASK;
    uint8_t RCC_CFGR2_PREDIV2_START;
    uint32_t RCC_CFGR2_PREDIV2_MASK;
    uint8_t RCC_CFGR2_PREDIV_START;
    uint32_t RCC_CFGR2_PREDIV_MASK;
    uint8_t RCC_CFGR2_PLLXTPRE_BIT;

    uint8_t PLLSRC_HSI_SELECTED;
    uint8_t PLLSRC_HSE_SELECTED;

    uint8_t SW_HSI_SELECTED;
    uint8_t SW_HSE_SELECTED;
    uint8_t SW_PLL_SELECTED;
};
